name: experts_legal_consultation
description: Experts for Collection Attorney & Agencies client consultation app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
 file_picker: 8.3.7
  image_picker: ^1.1.2
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/experts_logo.png
    - assets/images/court_background.png
